#pragma once

static const char OVERLAY_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"es\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>Spotify Overlay</title>\n"
"<style>\n"
"@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&display=swap');\n"
"body{margin:0;background:transparent;font-family:'Outfit',system-ui,sans-serif;display:flex;justify-content:center;align-items:flex-start;height:100vh;padding-top:40px;overflow:hidden;}\n"
".card{width:450px;min-height:110px;background:rgba(15,15,20,0.85);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);color:#fff;display:flex;padding:16px;border-radius:24px;align-items:center;gap:16px;box-shadow:0 10px 40px rgba(0,0,0,0.5),inset 0 1px 1px rgba(255,255,255,0.1);border:1px solid rgba(255,255,255,0.05);transition:all 0.5s cubic-bezier(0.34,1.56,0.64,1);opacity:1;transform:translateY(0) scale(1);overflow:hidden;}\n"
".card.hidden{opacity:0;transform:translateY(-40px) scale(0.9);pointer-events:none;}\n"
".art-container{width:76px;height:76px;flex-shrink:0;border-radius:50%;box-shadow:0 4px 15px rgba(0,0,0,0.6);background:#111;}\n"
"img{width:100%;height:100%;border-radius:50%;object-fit:cover;animation:spin 6s linear infinite;}\n"
"img.paused{animation-play-state:paused;}\n"
".info{flex:1;overflow:hidden;display:flex;flex-direction:column;justify-content:center;}\n"
".title-container,.artist-container{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}\n"
".title{font-size:19px;font-weight:700;letter-spacing:0.3px;margin-bottom:2px;text-shadow:0 2px 4px rgba(0,0,0,0.5);}\n"
".artist{opacity:0.8;font-size:14px;font-weight:400;margin-bottom:10px;text-shadow:0 1px 3px rgba(0,0,0,0.5);}\n"
".progress-container{display:flex;align-items:center;gap:12px;}\n"
".time{font-size:12px;opacity:0.7;font-family:'Outfit',monospace;font-weight:600;min-width:35px;text-align:center;}\n"
".bar{flex:1;height:6px;background:rgba(255,255,255,0.15);border-radius:999px;overflow:hidden;box-shadow:inset 0 1px 2px rgba(0,0,0,0.2);}\n"
".progress{height:100%;background:linear-gradient(90deg,#1db954,#1ed760);width:0%;transition:width 0.1s linear;box-shadow:0 0 8px rgba(29,185,84,0.6);}\n"
".track-change{animation:slideDownFade 0.7s cubic-bezier(0.34,1.56,0.64,1);}\n"
"@keyframes slideDownFade{0%{opacity:0;transform:translateY(-40px) scale(0.85);}100%{opacity:1;transform:translateY(0) scale(1);}}\n"
"@keyframes spin{100%{transform:rotate(360deg);}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div id=\"card-wrapper\">\n"
"<div class=\"card hidden\" id=\"card\">\n"
"<div class=\"art-container\"><img id=\"albumArt\" src=\"\" class=\"paused\" /></div>\n"
"<div class=\"info\">\n"
"<div class=\"title-container\"><div class=\"title\" id=\"trackTitle\"></div></div>\n"
"<div class=\"artist-container\"><div class=\"artist\" id=\"trackArtist\"></div></div>\n"
"<div class=\"progress-container\">\n"
"<span class=\"time\" id=\"currentTime\">0:00</span>\n"
"<div class=\"bar\"><div class=\"progress\" id=\"progressBar\"></div></div>\n"
"<span class=\"time\" id=\"totalTime\">0:00</span>\n"
"</div>\n"
"</div>\n"
"</div>\n"
"</div>\n"
"<script>\n"
"(function(){'use strict';var t='',e=0,n=1,s=false,o=Date.now();\n"
"function u(ms){if(!ms||isNaN(ms))return'0:00';var ts=Math.floor(ms/1000);return Math.floor(ts/60)+':'+(ts%60<10?'0':'')+ts%60}\n"
"function c(d){var cd=document.getElementById('card');if(!cd)return;\n"
"if(!d||!d.title){if(!cd.classList.contains('hidden'))cd.classList.add('hidden');t='';s=false;return}\n"
"n=d.duration_ms||1;s=d.isPlaying||false;\n"
"if(!s){if(!cd.classList.contains('hidden'))cd.classList.add('hidden')}else{if(cd.classList.contains('hidden'))cd.classList.remove('hidden')}\n"
"if(Math.abs(e-(d.progress_ms||0))>2000)e=d.progress_ms||0;o=Date.now();\n"
"var a=document.getElementById('albumArt');if(a){\n"
"var ar=d.albumArt||'';if(ar&&a.getAttribute('src')!==ar)a.setAttribute('src',ar);\n"
"if(s)a.classList.remove('paused');else a.classList.add('paused')}\n"
"if(t!==d.title){t=d.title;e=d.progress_ms||0;var ap=(d.app||'Spotify').replace('.exe','');\n"
"var te=document.getElementById('trackTitle');if(te)te.innerText=d.title;\n"
"var ae=document.getElementById('trackArtist');if(ae)ae.innerText=d.artist+' \\u2022 '+ap;\n"
"var tl=document.getElementById('totalTime');if(tl)tl.innerText=u(d.duration_ms);\n"
"cd.classList.remove('track-change');void cd.offsetWidth;cd.classList.add('track-change')}else{\n"
"var tl2=document.getElementById('totalTime');if(tl2)tl2.innerText=u(d.duration_ms)}}\n"
"function i(){if(!t)return;\n"
"if(s){var n2=Date.now();e+=n2-o;o=n2}else{o=Date.now()}\n"
"if(e>n)e=n;var p=(e/n)*100;\n"
"var b=document.getElementById('progressBar');var ct=document.getElementById('currentTime');\n"
"if(b)b.style.width=p+'%';if(ct)ct.innerText=u(e)}\n"
"function e2(){var h=window.location.hostname||'localhost',p='9274',url='http://'+h+':'+p+'/events';\n"
"var src=new EventSource(url);\n"
"src.addEventListener('media',function(ev){try{c(JSON.parse(ev.data))}catch(err){}});\n"
"src.onerror=function(){src.close();setTimeout(e2,2000)}}\n"
"e2();setInterval(i,100)})();\n"
"</script>\n"
"</body>\n"
"</html>\n";
